const CV = () => {
  return (
    <div className="bg-white p-8 md:p-16 max-w-[800px] mx-auto text-gray-800 font-sans shadow-lg my-10 border-t-8 border-orange-500">
      {/* HEADER */}
      <header className="border-b-2 border-gray-100 pb-6 mb-6">
        <h1 className="text-4xl font-bold text-gray-900 uppercase tracking-tight">Mahin Jaman</h1>
        <p className="text-orange-600 font-mono font-bold mt-1 text-lg">Full-Stack Web Developer</p>
        
        <div className="flex flex-wrap gap-4 mt-4 text-sm text-gray-600">
          <span className="flex items-center gap-1">📍 Dhaka, Bangladesh</span>
          <span className="flex items-center gap-1">📧 mahinjaman01@gmail.com</span>
          <a href="https://github.com/mahinjaman" className="text-blue-600 underline">github.com/mahinjaman</a>
          <a href="https://linkedin.com/in/mahin-jaman" className="text-blue-600 underline">linkedin.com/mahin-jaman</a>
        </div>
      </header>

      {/* SUMMARY */}
      <section className="mb-8">
        <h2 className="text-xl font-bold text-gray-900 border-l-4 border-orange-500 pl-3 mb-3 uppercase tracking-wide">Professional Summary</h2>
        <p className="text-gray-700 leading-relaxed">
          Dedicated Full-Stack Web Developer with over 2 years of experience in building scalable web applications. Currently pursuing Computer Science & Technology (CST). Expert in the MERN stack with a strong focus on writing clean, maintainable code and designing efficient database architectures.
        </p>
      </section>

      {/* SKILLS */}
      <section className="mb-8">
        <h2 className="text-xl font-bold text-gray-900 border-l-4 border-orange-500 pl-3 mb-3 uppercase tracking-wide">Technical Skills</h2>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <p className="font-bold text-gray-800">Frontend:</p>
            <p className="text-gray-700">React.js, Next.js, Tailwind CSS, Redux Toolkit</p>
          </div>
          <div>
            <p className="font-bold text-gray-800">Backend:</p>
            <p className="text-gray-700">Node.js, Express.js, Python, REST APIs</p>
          </div>
          <div>
            <p className="font-bold text-gray-800">Databases:</p>
            <p className="text-gray-700">MongoDB (NoSQL), MySQL (Relational)</p>
          </div>
          <div>
            <p className="font-bold text-gray-800">Tools:</p>
            <p className="text-gray-700">Git, GitHub, JWT, Framer Motion</p>
          </div>
        </div>
      </section>

      {/* EXPERIENCE */}
      <section className="mb-8">
        <h2 className="text-xl font-bold text-gray-900 border-l-4 border-orange-500 pl-3 mb-3 uppercase tracking-wide">Work Experience</h2>
        <div className="mb-4">
          <div className="flex justify-between items-center mb-1">
            <h3 className="font-bold text-lg text-gray-800">Full-Stack Developer (Independent)</h3>
            <span className="text-gray-500 text-sm italic">2023 – Present</span>
          </div>
          <ul className="list-disc ml-5 text-gray-700 space-y-1">
            <li>Developed high-performance web applications using the MERN stack.</li>
            <li>Designed and optimized database schemas in MongoDB and MySQL.</li>
            <li>Implemented secure authentication systems using JWT and managed state with Redux.</li>
          </ul>
        </div>
      </section>

      {/* EDUCATION */}
      <section className="mb-8">
        <h2 className="text-xl font-bold text-gray-900 border-l-4 border-orange-500 pl-3 mb-3 uppercase tracking-wide">Education</h2>
        <div className="flex justify-between items-center">
          <div>
            <h3 className="font-bold text-gray-800">Diploma in Computer Science & Technology</h3>
            <p className="text-gray-600">Institute Name (Ongoing)</p>
          </div>
          <span className="text-gray-500 italic text-sm">CST Student</span>
        </div>
      </section>

      {/* FOOTER FOR PRINT */}
      <footer className="mt-12 text-center text-gray-400 text-xs border-t pt-4">
        Generated by Mahin Jaman Portfolio System
      </footer>
    </div>
  );
};

export default CV;